server:
  port: ${helidon.port:8445}
  host: 0.0.0.0
  max-header-size: 65536
  tls:
    protocols:
      - TLSv1.2
      - TLSv1.3
    cipher-suite:
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_AES_128_GCM_SHA256
      - TLS_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
      - TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
      - TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
    trust:
      keystore:
        type: "${helidon.keystore.type:JKS}"
        passphrase: "${dtv.mobile.keystore.password}"
        trust-store: true
        resource:
          path: "../xyz_pos/mobile.keystore"
    private-key:
      keystore:
        type: "${helidon.keystore.type:JKS}"
        passphrase: "${dtv.mobile.keystore.password}"
        key:
          alias: "${dtv.mobile.keystore.alias}"
        resource:
          path: "../xyz_pos/mobile.keystore"
